install script: trap signals INT, TERM with a cleanup function

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2912,6 +2912,13 @@ echo "Usage: install -k | -i | -u [addonname] | -b | -r backupname | -l | -c | -
     -h | --help             Show help"
 }
 
+function cleanup(){
+    # set terminal back to normal
+    tput sgr0
+
+    # maybe cleanup some more things you know better
+}
+
 # remove last install log file
 if [ -f ${LOGFILE} ]
 then
@@ -2935,6 +2942,8 @@ fi
 
 set -- $options
 
+# catch ctrl-c
+trap cleanup INT TERM
 
 while [ $# -gt 0 ]
 do
