*Use the idea of yoyz (Johann) to get a default/shinken file. setup.py will generate it. *Update init.d scripts with LSB ones :)

diff --git a/bin/init.d/shinken-poller b/bin/init.d/shinken-poller
--- a/bin/init.d/shinken-poller
+++ b/bin/init.d/shinken-poller
@@ -1,62 +1,168 @@
-#!/bin/bash
+#! /bin/sh
+### BEGIN INIT INFO
+# Provides:          shinken-poller
+# Required-Start:    
+# Required-Stop:     
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Start Shinken poller daemon
+# Description:       Shinken is a monitoring tool and the Poller
+#                    is one of its daemon. This one get configuration from the arbiter
+#                    poller some checks and put them in queues for
+#                    other daemons
+### END INIT INFO
+
+# Author: Gabes Jean <naparuba@gmail.com>
+
+# Do NOT "set -e"
+#set -x
+
+NAME=shinken-poller
+
+# Read configuration variable file if it is present
+[ -r /etc/default/shinken ] && . /etc/default/shinken
+
+
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="Start Shinken poller daemon"
+
+#DAEMON is set in /etc/default/$NAME
+#DAEMON=/usr/sbin/$NAME
+DAEMON_ARGS=" -d -r -c $POLLERCFG"
+#PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
+
+# Exit if the package is not installed
+[ -x "$POLLERDAEMON" ] || exit 0
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
+. /lib/lsb/init-functions
+
 #
-# Shinken        Starts Shinken
+# Function that starts the daemon/service
 #
-#
-# chkconfig: 345 98 02
-# description: Start Shinken poller daemon
-
-# Source function library.
-if [ -f /etc/init.d/functions ]; then
-        . /etc/init.d/functions
-fi
-
-SHINKEN_USER=shinken
-SHINKEN_GROUP=shinken
-
-SHINKEN_BIN=/usr/local/shinken/bin
-SHINKEN_VAR=/usr/local/shinken/var/
-
-start() {
-        echo "Starting Shinken Poller daemon  ..."
-        su - $SHINKEN_USER -c "$SHINKEN_BIN/launch_poller.sh"
-#        chown -R $SHINKEN_GROUP:$NAGIOS_GROUP $SHINKEN_VAR
-        echo_success 
-        echo
-
+do_start()
+{
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+        #start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+	#	|| return 1
+	#start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+	#	$DAEMON_ARGS \
+	#	|| return 2
+        #DOn't like this start-stop thing. If someone know how it works,
+        #just change the code below, thanks.
+        $POLLERDAEMON $DAEMON_ARGS
+	return $?
+	# Add code here, if necessary, that waits for the process to be ready
+	# to handle requests from services started subsequently which depend
+	# on this one.  As a last resort, sleep for some time.
 }
 
-stop() {
-        echo "Stopping Shinken Poller daemon  ..."
-        su - $SHINKEN_USER -c "$SHINKEN_BIN/stop_poller.sh"
-        #sleep 3
-        #count=$(ps aux | grep python2.6 | grep -v grep | wc -l)
-        #if [ $count -gt 0 ]; then
-        #    killall python2.6
-        #fi
-        echo_success 
-        echo
- 
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+#	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+#	RETVAL="$?"
+#	[ "$RETVAL" = 2 ] && return 2
+	# Wait for children to finish too if this is a daemon that forks
+	# and if the daemon is only ever run from this initscript.
+	# If the above conditions are not satisfied then add some other code
+	# that waits for the process to drop all resources that could be
+	# needed by services started subsequently.  A last resort is to
+	# sleep for some time.
+#	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+#	[ "$?" = 2 ] && return 2
+	# Many daemons don't delete their pidfiles when they exit.
+#	rm -f $PIDFILE
+#	return "$RETVAL"
+        kill `cat $POLLERPID`
+	return $?
+}
+
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+	#
+	# If the daemon can reload its configuration without
+	# restarting (for example, when it is sent a SIGHUP),
+	# then implement that here.
+	#
+        start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+	return 0
 }
 
 case "$1" in
-  restart)
-        stop
-        start
-        exit 0
-        ;;
   start)
-        start
-        exit 0
-        ;;
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
   stop)
-       stop
-       exit 0
-        ;;
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
+  status)
+       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+       ;;
+  #reload|force-reload)
+	#
+	# If do_reload() is not implemented then leave this commented out
+	# and leave 'force-reload' as an alias for 'restart'.
+	#
+	#log_daemon_msg "Reloading $DESC" "$NAME"
+	#do_reload
+	#log_end_msg $?
+	#;;
+  restart|force-reload)
+	#
+	# If the "reload" option is implemented then remove the
+	# 'force-reload' alias
+	#
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+	  	# Failed to stop
+		log_end_msg 1
+		;;
+	esac
+	;;
   *)
-        echo $"Usage: $0 {start|stop|restart}"
-        exit 2
+	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	exit 3
+	;;
 esac
 
-exit $?
-
+:
