* First commit to try to fix #729700

diff --git a/debian/shinken-common.postrm b/debian/shinken-common.postrm
--- a/debian/shinken-common.postrm
+++ b/debian/shinken-common.postrm
@@ -3,12 +3,103 @@
 
 set -e
 
-update-rc.d -f shinken remove
+case "$1" in
+  remove)
+    # This package is being removed, but its configuration has not yet
+    # been purged.
+    :
 
-update-rc.d -f shinken-arbiter remove
-update-rc.d -f shinken-scheduler remove
-update-rc.d -f shinken-poller remove
-update-rc.d -f shinken-broker remove
-update-rc.d -f shinken-receiver remove
-update-rc.d -f shinken-reactionner remove
+    ## Removes directory stat
+    dpkg-statoverride --remove /var/run/shinken
+    dpkg-statoverride --remove /var/log/shinken
+    dpkg-statoverride --remove /var/lib/shinken
+
+    ## Ensure /var/run/shinken is removed
+    rm -rf /var/run/shinken || return 0
+    rm -rf /var/lib/shinken || return 0
+
+    ;;
+  purge)
+    # This package has previously been removed and is now having
+    # its configuration purged from the system.
+    :
+
+    ## No need init.d autostart anymore
+    update-rc.d -f shinken remove > /dev/null
+    update-rc.d -f shinken-arbiter remove > /dev/null
+    update-rc.d -f shinken-scheduler remove > /dev/null
+    update-rc.d -f shinken-poller remove > /dev/null
+    update-rc.d -f shinken-broker remove > /dev/null
+    update-rc.d -f shinken-receiver remove > /dev/null
+    update-rc.d -f shinken-reactionner remove > /dev/null
+
+    ## No need shinken user anymore
+    #userdel shinken >/dev/null 2>&1 || true
+
+    ## No need shinken group anymore
+    #groupdel shinken >/dev/null 2>&1 || true
+
+    ;;
+  disappear)
+    if test "$2" != overwriter; then
+      echo "$0: undocumented call to \`postrm $*'" 1>&2
+      exit 0
+    fi
+    # This package has been completely overwritten by package $3
+    # (version $4).  All our files are already gone from the system.
+    # This is a special case: neither "prerm remove" nor "postrm remove"
+    # have been called, because dpkg didn't know that this package would
+    # disappear until this stage.
+    :
+
+    ;;
+  upgrade)
+    # About to upgrade FROM THIS VERSION to version $2 of this package.
+    # "prerm upgrade" has been called for this version, and "preinst
+    # upgrade" has been called for the new version.  Last chance to
+    # clean up.
+    :
+
+    ;;
+  failed-upgrade)
+    # About to upgrade from version $2 of this package TO THIS VERSION.
+    # "prerm upgrade" has been called for the old version, and "preinst
+    # upgrade" has been called for this version.  This is only used if
+    # the previous version's "postrm upgrade" couldn't handle it and
+    # returned non-zero. (Fix old postrm bugs here.)
+    :
+
+    ;;
+  abort-install)
+    # Back out of an attempt to install this package.  Undo the effects of
+    # "preinst install...".  There are two sub-cases.
+    :
+
+    if test "${2+set}" = set; then
+      # When the install was attempted, version $2's configuration
+      # files were still on the system.  Undo the effects of "preinst
+      # install $2".
+      :
+
+    else
+      # We were being installed from scratch.  Undo the effects of
+      # "preinst install".
+      :
+
+    fi ;;
+  abort-upgrade)
+    # Back out of an attempt to upgrade this package from version $2
+    # TO THIS VERSION.  Undo the effects of "preinst upgrade $2".
+    :
+
+    ;;
+  *) echo "$0: didn't understand being called with \`$1'" 1>&2
+     exit 0;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+#DEBHELPER#
+
+exit 0
 
